import type { Blunder } from "../../types";

// Sample puzzles shown when no games have been analyzed yet.
// Each puzzle has one clearly winning capture that the player "missed".
export const defaultPuzzles: Blunder[] = [
  {
    // White rook on d3 can capture the unprotected black queen on d6
    fen: "4k3/8/3q4/8/8/3R4/8/7K w - - 0 1",
    movePlayed: "Rd1",
    moveFrom: "d3",
    moveTo: "d1",
    bestMove: "Rxd6",
    bestMoveFrom: "d3",
    bestMoveTo: "d6",
    evalBefore: 900,
    evalAfter: 0,
    evalDrop: 900,
    moveNumber: 20,
    playerColor: "white",
    gameUrl: "#",
    opponent: "Sample",
    gameResult: "loss",
    timeClass: "rapid",
    pieceMoved: "R",
    wasCapture: false,
    bestMoveWasCapture: true,
    gamePhase: "middlegame",
    opening: "Sample Puzzle",
  },
  {
    // White rook on a1 can capture the unprotected black rook on a5
    fen: "7k/8/8/r7/8/8/8/R6K w - - 0 1",
    movePlayed: "Rb1",
    moveFrom: "a1",
    moveTo: "b1",
    bestMove: "Rxa5",
    bestMoveFrom: "a1",
    bestMoveTo: "a5",
    evalBefore: 500,
    evalAfter: 0,
    evalDrop: 500,
    moveNumber: 42,
    playerColor: "white",
    gameUrl: "#",
    opponent: "Sample",
    gameResult: "loss",
    timeClass: "rapid",
    pieceMoved: "R",
    wasCapture: false,
    bestMoveWasCapture: true,
    gamePhase: "endgame",
    opening: "Sample Puzzle",
  },
  {
    // White knight on e4 can capture the unprotected black rook on f6
    fen: "4k3/8/5r2/8/4N3/8/8/7K w - - 0 1",
    movePlayed: "Nd2",
    moveFrom: "e4",
    moveTo: "d2",
    bestMove: "Nxf6",
    bestMoveFrom: "e4",
    bestMoveTo: "f6",
    evalBefore: 500,
    evalAfter: 0,
    evalDrop: 500,
    moveNumber: 35,
    playerColor: "white",
    gameUrl: "#",
    opponent: "Sample",
    gameResult: "loss",
    timeClass: "rapid",
    pieceMoved: "N",
    wasCapture: false,
    bestMoveWasCapture: true,
    gamePhase: "endgame",
    opening: "Sample Puzzle",
  },
  {
    // White bishop on d4 can capture the unprotected black knight on e5
    fen: "4k3/8/8/4n3/3B4/8/8/7K w - - 0 1",
    movePlayed: "Bc3",
    moveFrom: "d4",
    moveTo: "c3",
    bestMove: "Bxe5",
    bestMoveFrom: "d4",
    bestMoveTo: "e5",
    evalBefore: 300,
    evalAfter: 0,
    evalDrop: 300,
    moveNumber: 28,
    playerColor: "white",
    gameUrl: "#",
    opponent: "Sample",
    gameResult: "loss",
    timeClass: "rapid",
    pieceMoved: "B",
    wasCapture: false,
    bestMoveWasCapture: true,
    gamePhase: "endgame",
    opening: "Sample Puzzle",
  },
  {
    // White queen on g1 can capture the unprotected black bishop on c5
    fen: "4k3/8/8/2b5/8/8/8/6QK w - - 0 1",
    movePlayed: "Qg2",
    moveFrom: "g1",
    moveTo: "g2",
    bestMove: "Qxc5",
    bestMoveFrom: "g1",
    bestMoveTo: "c5",
    evalBefore: 300,
    evalAfter: 0,
    evalDrop: 300,
    moveNumber: 22,
    playerColor: "white",
    gameUrl: "#",
    opponent: "Sample",
    gameResult: "loss",
    timeClass: "rapid",
    pieceMoved: "Q",
    wasCapture: false,
    bestMoveWasCapture: true,
    gamePhase: "middlegame",
    opening: "Sample Puzzle",
  },
];
